//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMOEntities : DbContext
    {
        public static HMOEntities Instance { get; } = new HMOEntities();

        public HMOEntities()
            : base("name=HMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoronaTest> CoronaTest { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPerCoronaTest> UserPerCoronaTest { get; set; }
        public virtual DbSet<UserPerVaccination> UserPerVaccination { get; set; }
        public virtual DbSet<Vaccination> Vaccination { get; set; }
    }
}
