//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPerVaccination
    {
        public int Code_userPerVacc { get; set; }
        public int CodeUser_userPerVacc { get; set; }
        public int CodeVacc_userPerVacc { get; set; }
        public System.DateTime Date_userPerVacc { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vaccination Vaccination { get; set; }
    }
}
