//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Code_user { get; set; }
        public string FirstName_user { get; set; }
        public string LastName_user { get; set; }
        public string ID_user { get; set; }
        public System.DateTime DateOfBirth_user { get; set; }
        public string City_user { get; set; }
        public string Address_user { get; set; }
    
        public virtual UserPerCoronaTest UserPerCoronaTest { get; set; }
        public virtual UserPerVaccination UserPerVaccination { get; set; }
    }
}
