//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPerCoronaTest
    {
        public int Code_userPerCT { get; set; }
        public int CodeUser_userPerCT { get; set; }
        public int CodeCT_userPerCT { get; set; }
        public System.DateTime Date_userPerCT { get; set; }
        public bool Result_userPerCT { get; set; }
    
        public virtual CoronaTest CoronaTest { get; set; }
        public virtual User User { get; set; }
    }
}
